version: "3.9"

services:
  ww-api:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    container_name: ww-api
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB
    hostname: ww-api
    image: ww-api:local
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: .venv/bin/uvicorn app.main:api --workers 1 --host 0.0.0.0 --port 8080
    # command: /bin/bash
    # stdin_open: true
    # tty: true
    networks:
      ww:
        ipv4_address: 172.23.0.10
    ports:
      - 8080:8080/tcp
    restart: unless-stopped

networks:
  ww:
    name: python
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.254
